apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments-deployment
  labels:
    app: comments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templates-comments
  template:
    metadata:
      labels:
        app: templates-comments
    spec:
      containers:
      - name: comments-container
        imagePullPolicy: IfNotPresent
        image: comments
        ports:
        - containerPort: 4001

---

apiVersion: v1
kind: Service
metadata:
  name: comments-srv
spec:
  type: ClusterIP
  selector:
    app: templates-comments
  ports:
  - name: comments-port
    protocol: TCP
    port: 4001
    targetPort: 4001